alias: SWW Dagelijkse sturing met Tibber - Verbeterd v3
description: >
  Basis 45Â°C, boost naar 50Â°C op goedkoopste uur, onder 45Â°C altijd
  nood-bijverwarmen. Slimme sensor-wissel na 14:00u. Legionella heeft voorrang.
triggers:
  - trigger: homeassistant
    event: start
  - trigger: time
    at: "00:30:00"
  - trigger: time
    at: "14:00:00"
  - trigger: time
    at: "15:00:00"
  - trigger: time
    at: "16:00:00"
  - trigger: time
    at: "17:00:00"
  - trigger: time
    at: "22:00:00"
  - trigger: time_pattern
    hours: "*"
    minutes: "0"
conditions: []
actions:
  - if:
      - condition: template
        value_template: "{{ trigger.platform == 'homeassistant' }}"
    then:
      - action: notify.pushover_ha
        data:
          title: "[SWW] âœ… Automatisering gestart"
          message: >
            SWW-automatisering actief na HA herstart. Huidige temp: {{ sww_temp
            }}Â°C Huidig setpoint: {{ setpoint }}Â°C Huidige prijs: {{
            huidige_prijs }} ct/kWh

            {% if actieve_tijd not in [None, 'unknown', 'unavailable', ''] %}
            Goedkoopste uur {{ actieve_label }}: {{ (actieve_tijd |
            as_datetime).strftime('%H:%M') }} ({{ actieve_prijs }} ct/kWh) {% if
            legionella_moet_draaien %}âš ï¸ LET OP: Legionella heeft voorrang op
            dit uur ({{ legionella_dagen_geleden }} dagen geleden). {% endif %}
            {% elif now().hour >= 14 and not morgen_prijzen_bekend %} âš ï¸ Morgen
            prijzen nog niet bekend - wacht op Tibber update {% else %} âš ï¸
            Goedkoopste uur niet bekend - check Tibber-sensor {% endif %}
  - if:
      - condition: template
        value_template: "{{ now().hour in [14, 15, 16, 17, 22] }}"
    then:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ now().hour >= 14 and vandaag_goedkoopste_geweest and not
                  morgen_prijzen_bekend }}
            sequence:
              - action: notify.pushover_ha
                data:
                  title: "[SWW] â³ Prijzen nog niet bekend"
                  message: >
                    Morgen-prijzen nog niet beschikbaar om {{
                    now().strftime('%H:%M uur') }}. Goedkoopste uur vandaag ({{
                    (vandaag_tijd | as_datetime).strftime('%H:%M') }}) is al
                    geweest. Wacht op Tibber-update, check elk uur opnieuw.
                    Huidige temp: {{ sww_temp }}Â°C
          - conditions:
              - condition: template
                value_template: >-
                  {{ not gebruik_morgen_sensor and vandaag_tijd not in [None,
                  'unknown', 'unavailable', ''] }}
            sequence:
              - action: notify.pushover_ha
                data:
                  title: "[SWW] ðŸ“… Planning vandaag"
                  message: >
                    Goedkoopste uur vandaag: {{ (vandaag_tijd |
                    as_datetime).strftime('%H:%M uur') }} Prijs: {{
                    vandaag_prijs }} ct/kWh Huidige temp: {{ sww_temp }}Â°C
                    Huidig setpoint: {{ setpoint }}Â°C
          - conditions:
              - condition: template
                value_template: "{{ gebruik_morgen_sensor }}"
            sequence:
              - action: notify.pushover_ha
                data:
                  title: "[SWW] ðŸ“… Planning morgen"
                  message: >
                    Goedkoopste uur morgen: {{ (morgen_tijd |
                    as_datetime).strftime('%H:%M uur') }} Prijs: {{ morgen_prijs
                    }} ct/kWh {% if legionella_moet_draaien %}âš ï¸ Legionella
                    heeft voorrang ({{ legionella_dagen_geleden }} dagen
                    geleden). {% endif %}Huidige temp: {{ sww_temp }}Â°C Huidig
                    setpoint: {{ setpoint }}Â°C
        default:
          - action: notify.pushover_ha
            data:
              title: "[SWW] ðŸ“… Planning"
              message: >
                Boost op goedkoopste uur van de dag. Huidige temp: {{ sww_temp
                }}Â°C Huidig setpoint: {{ setpoint }}Â°C
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ legionella_heeft_voorrang }}"
        sequence:
          - action: notify.pushover_ha
            data:
              title: "[SWW] ðŸ”¥ Legionella actief"
              message: >
                SWW-boost overgeslagen op goedkoopste uur. Legionella Prevention
                heeft voorrang ({{ legionella_dagen_geleden }} dagen geleden).
                Water wordt nu opgewarmd naar â‰¥60Â°C gedurende 90 minuten.
      - conditions:
          - condition: template
            value_template: "{{ sww_temp < 45 }}"
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: climate.ecodan_heatpump_dhw_thermostaat
            data:
              temperature: 45
          - action: switch.turn_on
            target:
              entity_id: switch.ecodan_heatpump_set_forceer_sww
      - conditions:
          - condition: template
            value_template: "{{ sww_temp >= 45 and sww_temp < 50 }}"
          - condition: template
            value_template: "{{ is_goedkoop_uur }}"
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: climate.ecodan_heatpump_dhw_thermostaat
            data:
              temperature: 50
          - action: switch.turn_on
            target:
              entity_id: switch.ecodan_heatpump_set_forceer_sww
      - conditions:
          - condition: template
            value_template: "{{ sww_temp >= 50 }}"
          - condition: template
            value_template: "{{ is_goedkoop_uur }}"
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: climate.ecodan_heatpump_dhw_thermostaat
            data:
              temperature: 45
          - action: switch.turn_off
            target:
              entity_id: switch.ecodan_heatpump_set_forceer_sww
      - conditions:
          - condition: template
            value_template: "{{ sww_temp >= 45 }}"
          - condition: template
            value_template: "{{ not is_goedkoop_uur }}"
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: climate.ecodan_heatpump_dhw_thermostaat
            data:
              temperature: 45
          - action: switch.turn_off
            target:
              entity_id: switch.ecodan_heatpump_set_forceer_sww
variables:
  huidige_prijs: "{{ states('sensor.ab27hia_huidige_elektriciteitsprijs_2') | float(999) }}"
  vandaag_prijs: "{{ states('sensor.tibber_vandaag_laagste_prijs') | float(999) }}"
  vandaag_tijd: "{{ state_attr('sensor.tibber_vandaag_laagste_prijs', 'timestamp') }}"
  morgen_prijs: "{{ states('sensor.tibber_morgen_laagste_prijs') | float(999) }}"
  morgen_tijd: "{{ state_attr('sensor.tibber_morgen_laagste_prijs', 'timestamp') }}"
  sww_temp: "{{ states('sensor.ecodan_heatpump_sww_huidige_temp') | float(0) }}"
  setpoint: >-
    {{ state_attr('climate.ecodan_heatpump_dhw_thermostaat', 'temperature') |
    float(0) }}
  morgen_prijzen_bekend: >-
    {{ morgen_tijd not in [None, 'unknown', 'unavailable', ''] and morgen_prijs
    < 999 }}
  vandaag_goedkoopste_geweest: >-
    {% set vandaag_uur = vandaag_tijd | as_datetime %} {{ vandaag_uur != none
    and now().hour > vandaag_uur.hour }}
  gebruik_morgen_sensor: >-
    {{ now().hour >= 14 and vandaag_goedkoopste_geweest and
    morgen_prijzen_bekend }}
  actieve_prijs: "{{ morgen_prijs if gebruik_morgen_sensor else vandaag_prijs }}"
  actieve_tijd: "{{ morgen_tijd if gebruik_morgen_sensor else vandaag_tijd }}"
  actieve_label: "{{ 'morgen' if gebruik_morgen_sensor else 'vandaag' }}"
  is_goedkoop_uur: >-
    {% set goedkoop_uur = actieve_tijd | as_datetime %} {{ goedkoop_uur != none
    and now().hour == goedkoop_uur.hour }}
  legionella_last: "{{ states('input_datetime.legionella_last_done') }}"
  legionella_dagen_geleden: |-
    {% if legionella_last in ['unknown', 'unavailable', ''] %}
      999
    {% else %}
      {{ ((as_timestamp(now()) - as_timestamp(legionella_last)) / 86400) | round(0) | int }}
    {% endif %}
  legionella_moet_draaien: "{{ legionella_dagen_geleden >= 14 }}"
  legionella_heeft_voorrang: "{{ legionella_moet_draaien and is_goedkoop_uur }}"
mode: single
max_exceeded: silent
